import {useCallback,useEffect,useRef,useState} from "react";
import {Plus,RefreshCw,Search,FolderOpen,Upload,Pencil,Trash2,RotateCcw} from "lucide-react";
import {command,subscribe} from "./bridge";
import {errorOf} from "./types";
import type {Price,PricingView,RemoteModel,PricingSettings,Rates} from "./usage-types";
import {emptyRates,date} from "./usage-types";
import UsageDialog from "./UsageDialog";
const labels: [keyof Rates,string][]=[["input","输入"],["output","输出"],["cacheRead","缓存读取"],["cacheWrite","缓存写入"],["cacheHour","缓存写入（1 小时）"],["imageInput","图片输入 Token"],["imageOutput","图片输出 Token"],["image","每张图片"]];
export default function Pricing({onDirtyChange}:{onDirtyChange:(dirty:boolean)=>void}) {
 const [state,setState]=useState<PricingView|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[query,setQuery]=useState(""),[page,setPage]=useState(0),[draft,setDraft]=useState<Price|null>(null),[tiers,setTiers]=useState("[]"),[catalog,setCatalog]=useState<"import"|"sync"|null>(null);
 const file=useRef<HTMLInputElement>(null);
 const load=useCallback(()=>command<PricingView>("get_pricing").then(setState).catch(e=>setError(errorOf(e).message)),[]);
 useEffect(()=>{void load();let disposed=false,clean=()=>{};void subscribe("pricing-state",()=>void load()).then(c=>disposed?c():clean=c);return()=>{disposed=true;clean();};},[load]);
 useEffect(()=>{onDirtyChange(!!draft||!!catalog);return()=>onDirtyChange(false);},[draft,catalog,onDirtyChange]);
 const run=async(f:()=>Promise<PricingView>)=>{if(busy)return;setBusy(true);setError("");try{setState(await f());return true;}catch(e){setError(errorOf(e).message);return false;}finally{setBusy(false);}};
 const edit=(value:unknown)=>command<PricingView>("update_pricing",{edit:value,expectedRevision:state!.revision});
 const prices=state?.prices.filter(p=>`${p.modelId} ${p.displayName} ${p.source}`.toLowerCase().includes(query.toLowerCase()))??[];
 const save=async()=>{if(!draft)return;try{const variants=JSON.parse(tiers);if(!Array.isArray(variants))throw Error("分层价格必须是数组");if(await run(()=>edit({op:"save",price:{...draft,variants}})))setDraft(null);}catch(e){setError(errorOf(e).message);}};
 const imported=async(f:File)=>{try{if(f.size>4*1024*1024)throw Error("导入文件超过 4 MiB");const raw=JSON.parse(await f.text());const values=Array.isArray(raw)?raw:raw.prices;if(!Array.isArray(values))throw Error("导入文件须为价格数组或包含 prices 数组");await run(()=>edit({op:"import",prices:values.map(p=>({displayName:p.modelId,source:"manual",fixed:true,variants:[],...p,rates:{...emptyRates,...p.rates}}))}));}catch(e){setError(errorOf(e).message);}};
 return <div className="pricing-page">
 <section className="usage-card pricing-source"><div><strong>LiteLLM</strong><label className="check-label"><input type="checkbox" checked={state?.settings.autoUpdate??true} disabled={!state||busy} onChange={e=>void run(()=>edit({op:"settings",settings:{...state!.settings,autoUpdate:e.target.checked}}))}/>自动更新</label></div><div className="pricing-times"><span>检查 {date(state?.sync.checkedAt)}</span><span>更新 {date(state?.sync.updatedAt)}</span></div><button className="secondary" disabled={busy} onClick={()=>void run(()=>command("sync_pricing"))}><RefreshCw size={14}/>立即更新</button>{state?.sync.error&&<div className="form-error" role="alert">{state.sync.error}</div>}</section>
 <section className="usage-card pricing-source"><div><strong>models.dev</strong><span className="status-pill">{state?.settings.modelsDevEnabled?"自动同步已开启":"自动同步已关闭"}</span></div><div className="pricing-times"><span>检查 {date(state?.modelsDevSync.checkedAt)}</span><span>同步 {date(state?.modelsDevSync.updatedAt)}</span></div><button className="secondary" onClick={()=>setCatalog("sync")}>同步设置</button><button className="secondary" onClick={()=>setCatalog("import")}>导入模型</button>{state?.modelsDevSync.error&&<div className="form-error" role="alert">{state.modelsDevSync.error}</div>}</section>
 {error&&<div role="alert" className="form-error">{error}</div>}
 <div className="pricing-toolbar"><label className="usage-search"><Search size={14}/><input placeholder="搜索模型价格" aria-label="搜索模型价格" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/></label><button className="secondary" onClick={()=>{setDraft({modelId:"",displayName:"",source:"manual",fixed:true,rates:{...emptyRates},variants:[]});setTiers("[]");setError("");}}><Plus size={14}/>新增</button><button className="secondary" onClick={()=>file.current?.click()}><Upload size={14}/>批量导入</button><input hidden ref={file} type="file" accept="application/json,.json" onChange={e=>{const f=e.target.files?.[0];if(f)void imported(f);e.target.value="";}}/></div>
 <section className="usage-card"><div className="usage-table-scroll"><table className="usage-table price-table"><thead><tr><th>模型</th><th>输入</th><th>输出</th><th>缓存读取</th><th>缓存写入</th><th>来源</th><th>操作</th></tr></thead><tbody>{prices.slice(page*30,(page+1)*30).map(p=><tr key={p.modelId}><td title={p.modelId}>{p.modelId}{p.variants.length>0&&<span>{p.variants.length} 个计费分层</span>}</td>{(["input","output","cacheRead","cacheWrite"] as const).map(k=><td key={k}>{p.rates[k]??"未定价"}</td>)}<td>{p.source}{p.fixed&&<span>固定</span>}</td><td><div className="table-actions"><button className="icon-button" aria-label={`编辑 ${p.modelId}`} onClick={()=>{setDraft(structuredClone(p));setTiers(JSON.stringify(p.variants,null,2));setError("");}}><Pencil size={14}/></button><button className="icon-button" aria-label={`恢复自动价格 ${p.modelId}`} disabled={busy||!p.fixed} onClick={()=>void run(()=>edit({op:"automatic",id:p.modelId}))}><RotateCcw size={14}/></button><button className="icon-button" aria-label={`删除价格 ${p.modelId}`} disabled={busy} onClick={()=>{if(window.confirm(`删除 ${p.modelId} 的价格？`))void run(()=>edit({op:"delete",id:p.modelId}));}}><Trash2 size={14}/></button></div></td></tr>)}</tbody></table>{!prices.length&&<div className="usage-empty">没有匹配的模型</div>}</div><div className="usage-pagination"><span>{prices.length} 个模型 · USD / 百万 Token</span><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>上一页</button><span>{page+1} / {Math.max(1,Math.ceil(prices.length/30))}</span><button disabled={(page+1)*30>=prices.length} onClick={()=>setPage(p=>p+1)}>下一页</button></div></section>
 <div className="pricing-file"><span title={state?.configPath}>{state?.configPath}</span><button className="text-button" onClick={()=>void command("open_pricing_folder").catch(e=>setError(errorOf(e).message))}><FolderOpen size={14}/>打开目录</button><button className="text-button" disabled={busy} onClick={()=>void run(()=>command("reload_pricing"))}>重新载入</button></div>
 {draft&&<UsageDialog title="模型定价" close={()=>setDraft(null)}><form className="usage-form" onSubmit={e=>{e.preventDefault();void save();}}><label>模型 ID<input required maxLength={256} value={draft.modelId} onChange={e=>setDraft({...draft,modelId:e.target.value,displayName:e.target.value})}/></label><div className="rate-grid">{labels.map(([k,n])=><label key={k}>{n} · {k==="image"?"USD / 张":"USD / M Token"}<input type="number" min="0" step="any" placeholder="未定价" value={draft.rates[k]??""} onChange={e=>setDraft({...draft,rates:{...draft.rates,[k]:e.target.value||null}})}/></label>)}</div><details><summary>服务等级与长上下文分层</summary><textarea aria-label="分层价格 JSON" spellCheck={false} value={tiers} onChange={e=>setTiers(e.target.value)}/></details>{error&&<div className="form-error" role="alert">{error}</div>}<button className="primary" disabled={busy}>保存固定价格</button></form></UsageDialog>}
 {catalog&&state&&<Catalog mode={catalog} state={state} close={()=>setCatalog(null)} saved={s=>{setState(s);setCatalog(null);}}/>}
 </div>;
}
function Catalog({mode,state,close,saved}:{mode:"import"|"sync";state:PricingView;close:()=>void;saved:(s:PricingView)=>void}) {
 const [models,setModels]=useState<RemoteModel[]>([]),[cfg,setCfg]=useState<PricingSettings>(structuredClone(state.settings)),[selected,setSelected]=useState(new Set<string>()),[query,setQuery]=useState(""),[provider,setProvider]=useState(""),[page,setPage]=useState(0),[error,setError]=useState(""),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false);
 const load=useCallback(async(force=false)=>{setLoading(true);setError("");try{setModels(await command<RemoteModel[]>("list_models_dev",{force}));}catch(e){setError(errorOf(e).message);}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);
 const rows=models.filter(m=>(!provider||m.provider===provider)&&`${m.name} ${m.modelId}`.toLowerCase().includes(query.toLowerCase()));
 const checked=(m:RemoteModel)=>mode==="import"?selected.has(m.key):cfg.selected.includes(m.key)||(cfg.includeCommon&&m.common&&!cfg.excluded.includes(m.key));
 const toggle=(items:RemoteModel[],enabled:boolean)=>{if(mode==="import"){const s=new Set(selected);items.forEach(m=>enabled?s.add(m.key):s.delete(m.key));setSelected(s);}else{const s=new Set(cfg.selected),x=new Set(cfg.excluded);items.forEach(m=>{if(enabled){s.add(m.key);x.delete(m.key);}else{s.delete(m.key);x.add(m.key);}});setCfg({...cfg,selected:[...s],excluded:[...x]});}};
 const save=async()=>{setSaving(true);setError("");try{const next=mode==="import"?await command<PricingView>("import_models_dev",{keys:[...selected],expectedRevision:state.revision}):await command<PricingView>("update_pricing",{edit:{op:"settings",settings:cfg},expectedRevision:state.revision});saved(next);}catch(e){setError(errorOf(e).message);}finally{setSaving(false);}};
 return <UsageDialog title={mode==="import"?"从 models.dev 导入":"models.dev 自动同步"} wide close={close}><div className="usage-form">
 {mode==="sync"&&<><label className="check-label"><input type="checkbox" checked={cfg.modelsDevEnabled} onChange={e=>setCfg({...cfg,modelsDevEnabled:e.target.checked})}/>自动同步</label><label className="check-label"><input type="checkbox" checked={cfg.includeCommon} onChange={e=>setCfg({...cfg,includeCommon:e.target.checked})}/>常用模型</label></>}
 <div className="usage-filters"><label>供应商<select value={provider} onChange={e=>{setProvider(e.target.value);setPage(0);}}><option value="">全部供应商</option>{[...new Set(models.map(m=>m.provider))].sort().map(p=><option key={p}>{p}</option>)}</select></label><label>模型<input placeholder="搜索模型" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/></label><button className="secondary" disabled={loading} onClick={()=>void load(true)}><RefreshCw size={14}/>重新读取</button></div>
 {error&&<div className="form-error" role="alert">{error}</div>}
 <div className="catalog-select"><span>{rows.length} 个模型 · 已选 {mode==="import"?selected.size:models.filter(checked).length}</span><button className="text-button" onClick={()=>toggle(rows,true)}>全选筛选结果</button><button className="text-button" onClick={()=>toggle(rows,false)}>清空筛选结果</button></div>
 <div className="catalog-list">{rows.slice(page*60,(page+1)*60).map(m=><label key={m.key}><input type="checkbox" checked={checked(m)} onChange={e=>toggle([m],e.target.checked)}/><span><strong>{m.modelId}</strong><span>{m.provider}{m.common?" · 常用":""}</span></span><span>{m.price.rates.input??"—"} / {m.price.rates.output??"—"}</span></label>)}{loading&&<div className="usage-empty">正在读取模型…</div>}</div>
 <div className="usage-pagination"><button disabled={!page} onClick={()=>setPage(p=>p-1)}>上一页</button><span>{page+1} / {Math.max(1,Math.ceil(rows.length/60))}</span><button disabled={(page+1)*60>=rows.length} onClick={()=>setPage(p=>p+1)}>下一页</button></div>
 {mode==="sync"&&<details><summary>指定模型 {cfg.selected.length} · 排除项 {cfg.excluded.length}</summary><label>指定模型<textarea aria-label="指定模型" value={cfg.selected.join("\n")} onChange={e=>setCfg({...cfg,selected:[...new Set(e.target.value.split("\n").map(s=>s.trim()).filter(Boolean))]})}/></label><label>排除项<textarea aria-label="排除项" value={cfg.excluded.join("\n")} onChange={e=>setCfg({...cfg,excluded:[...new Set(e.target.value.split("\n").map(s=>s.trim()).filter(Boolean))]})}/></label></details>}
 <button className="primary" disabled={saving||(mode==="import"&&!selected.size)} onClick={()=>void save()}>{mode==="import"?"导入固定价格":"保存同步设置"}</button>
 </div></UsageDialog>;
}
