import {useCallback,useEffect,useRef,useState} from "react";
import {RefreshCw,SlidersHorizontal} from "lucide-react";
import {command,subscribe} from "./bridge";
import {errorOf} from "./types";
import type {Dashboard,Filters,UsageState,UsageSettings,LogPage,UsageRecord,Group,Price} from "./usage-types";
import {number,money,date,totalTokens,speed} from "./usage-types";
import UsageDialog from "./UsageDialog";
import UsageChart from "./UsageChart";
import Pricing from "./Pricing";
const localDate=(n:number)=>{const d=new Date(n);return new Date(n-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
export function range(preset:string,start:string,end:string,live:boolean,now=Date.now()):Filters {
 const finish=live?now:Date.parse(end);
 const begin=preset==="custom"?Date.parse(start):preset==="today"?new Date(now).setHours(0,0,0,0):now-Number(preset)*86400000;
 return {start:Math.floor(begin/1000),end:Math.floor((preset==="custom"?finish:now)/1000)+1};
}
export default function Usage({onDirtyChange}:{onDirtyChange:(dirty:boolean)=>void}) {
 const [preset,setPreset]=useState("today"),[start,setStart]=useState(localDate(Date.now()-86400000)),[end,setEnd]=useState(localDate(Date.now())),[live,setLive]=useState(true);
 const [provider,setProvider]=useState(""),[model,setModel]=useState(""),[status,setStatus]=useState(""),[tab,setTab]=useState("overview"),[page,setPage]=useState(0);
 const [data,setData]=useState<Dashboard|null>(null),[logs,setLogs]=useState<LogPage|null>(null),[settings,setSettings]=useState<UsageState|null>(null),[edit,setEdit]=useState<UsageSettings|null>(null),[detail,setDetail]=useState<UsageRecord|null>(null);
 const [error,setError]=useState(""),[busy,setBusy]=useState(false),[visible,setVisible]=useState(document.visibilityState!=="hidden"),[nativeVisible,setNativeVisible]=useState(true),[updated,setUpdated]=useState(0);
 const generation=useRef(0),filters=useRef<Filters>({}),latest=useRef({preset,start,end,live,provider,model,status,page});latest.current={preset,start,end,live,provider,model,status,page};
 const load=useCallback(async()=>{
  const n=++generation.current,p=latest.current;const f={...range(p.preset,p.start,p.end,p.live),...(p.provider?{providerId:p.provider}:{}),...(p.model?{model:p.model}:{})};filters.current=f;
  if(!Number.isFinite(f.start)||!Number.isFinite(f.end)||f.end!<=f.start!){setError("请选择有效的时间范围");return;}
  setBusy(true);
  try{const [d,l,s]=await Promise.all([command<Dashboard>("get_usage_dashboard",{filters:f}),command<LogPage>("get_usage_logs",{filters:{...f,...(p.status?{status:Number(p.status)}:{})},page:p.page}),command<UsageState>("get_usage_state")]);if(n===generation.current){setData(d);setLogs(l);setSettings(s);setError(s.error??"");setUpdated(Date.now());}}
  catch(e){if(n===generation.current)setError(errorOf(e).message);}finally{if(n===generation.current)setBusy(false);}
 },[]);
 useEffect(()=>{let disposed=false;const clean:(()=>void)[]=[];void subscribe<boolean>("app-visibility",setNativeVisible).then(c=>disposed?c():clean.push(c));const f=()=>setVisible(document.visibilityState!=="hidden");document.addEventListener("visibilitychange",f);return()=>{disposed=true;generation.current++;clean.forEach(c=>c());document.removeEventListener("visibilitychange",f);};},[]);
 useEffect(()=>{if(visible&&nativeVisible&&tab!=="pricing")void load();},[preset,start,end,live,provider,model,status,page,tab,visible,nativeVisible,load]);
 useEffect(()=>{if(!visible||!nativeVisible||tab==="pricing"||!settings?.settings.refreshSeconds)return;const t=setInterval(()=>void load(),settings.settings.refreshSeconds*1000);return()=>clearInterval(t);},[visible,nativeVisible,tab,settings?.settings.refreshSeconds,load]);
 useEffect(()=>{onDirtyChange(!!edit);return()=>onDirtyChange(false);},[edit,onDirtyChange]);
 const reset=()=>setPage(0);
 const changeSettings=async(next:UsageSettings)=>{if(!settings)return;setBusy(true);try{setSettings(await command<UsageState>("set_usage_settings",{settings:next,expectedRevision:settings.revision}));setEdit(null);setError("");}catch(e){setError(errorOf(e).message);}finally{setBusy(false);}};
 const zoom=(a:number,b:number)=>{setPreset("custom");setStart(localDate(a*1000));setEnd(localDate(b*1000));setLive(false);reset();};
 const summary=data?.summary,tokens=summary?.tokens;
 const cache= tokens && [tokens.input,tokens.cacheRead,tokens.cacheWrite].every(v=>v!==null)?((tokens.cacheRead??0)/Math.max(1,(tokens.input??0)+(tokens.cacheRead??0)+(tokens.cacheWrite??0))*100).toFixed(1)+"%":tokens?.cacheRead!=null&&tokens.input!=null?((tokens.cacheRead)/Math.max(1,tokens.input+tokens.cacheRead+(tokens.cacheWrite??0))*100).toFixed(1)+"%":"未提供";
 return <section className="usage-page"><div className="page-heading"><h1>使用统计</h1><div className="heading-actions"><button className="secondary" disabled={!settings} onClick={()=>setEdit(structuredClone(settings!.settings))}><SlidersHorizontal size={14}/>记录设置</button><button className="secondary" disabled={busy} onClick={()=>void load()}><RefreshCw size={14} className={busy?"spin":""}/>刷新</button></div></div>
 <nav className="usage-tabs" aria-label="统计视图">{[["overview","概览"],["logs","请求日志"],["providers","供应商"],["models","模型"],["pricing","定价"]].map(([k,n])=><button key={k} className={tab===k?"active":""} onClick={()=>setTab(k)}>{n}</button>)}</nav>
 {error&&<div className="form-error" role="alert">{error}</div>}
 {tab==="pricing"?<Pricing onDirtyChange={onDirtyChange}/>:<>
 <div className="usage-filters"><label>时间范围<select value={preset} onChange={e=>{setPreset(e.target.value);reset();}}>{[["today","今日"],["1","最近 24 小时"],["7","最近 7 天"],["14","最近 14 天"],["30","最近 30 天"],["custom","自定义"]].map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label>供应商<select value={provider} onChange={e=>{setProvider(e.target.value);reset();}}><option value="">全部供应商</option>{data?.availableProviders.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>计价模型<select value={model} onChange={e=>{setModel(e.target.value);reset();}}><option value="">全部模型</option>{data?.availableModels.map(m=><option key={m}>{m}</option>)}</select></label><label>自动刷新<select aria-label="自动刷新" value={settings?.settings.refreshSeconds??30} disabled={!settings||busy} onChange={e=>void changeSettings({...settings!.settings,refreshSeconds:Number(e.target.value)})}>{[0,5,10,30,60].map(n=><option key={n} value={n}>{n?`${n} 秒`:"关闭"}</option>)}</select></label></div>
 {preset==="custom"&&<div className="usage-date-range"><label>开始<input type="datetime-local" value={start} onChange={e=>{setStart(e.target.value);reset();}}/></label><label>结束<input type="datetime-local" disabled={live} value={end} onChange={e=>{setEnd(e.target.value);reset();}}/></label><label className="check-label"><input type="checkbox" checked={live} onChange={e=>setLive(e.target.checked)}/>跟随当前时间</label></div>}
 {data&&data.precision==="day"&&<div className="usage-status">按日汇总 · {date(data.effectiveStart)} — {date(data.effectiveEnd)}</div>}
 {summary&&<div className="usage-metrics">{[["上游请求",number(summary.requests)],["成功率",summary.requests?`${(summary.successes/summary.requests*100).toFixed(1)}%`:"—"],["总 Token",number(totalTokens(summary.tokens))],["估算费用",money(summary.cost)],["输入",number(tokens?.input)],["输出",number(tokens?.output)],["缓存读取 / 写入",`${number(tokens?.cacheRead)} / ${number(tokens?.cacheWrite)}`],["缓存命中率",cache]].map(([name,v])=><div key={name}><span>{name}</span><strong>{v}</strong></div>)}</div>}
 {summary&&(summary.unpriced>0||summary.partial>0||summary.missingUsage>0||summary.gatewayErrors>0)&&<div className="usage-status">{[summary.unpriced&&`未定价 ${summary.unpriced}`,summary.partial&&`部分计价 ${summary.partial}`,summary.missingUsage&&`未报告用量 ${summary.missingUsage}`,summary.gatewayErrors&&`网关错误 ${summary.gatewayErrors}`].filter(Boolean).join(" · ")}</div>}
 {tab==="overview"&&data&&<><UsageChart data={data} zoom={zoom}/><div className="usage-two"><GroupTable kind="providers" rows={data.providers}/><GroupTable kind="models" rows={data.models}/></div></>}
 {(tab==="providers"||tab==="models")&&data&&<GroupTable kind={tab} rows={tab==="providers"?data.providers:data.models}/>}
 {tab==="logs"&&<section className="usage-card"><div className="usage-section-heading"><h2>请求日志</h2><label className="inline-label">状态码<input type="number" placeholder="全部" aria-label="状态码" min="100" max="599" value={status} onChange={e=>{setStatus(e.target.value);reset();}}/></label></div><div className="usage-table-scroll"><table className="usage-table logs-table"><thead><tr>{["时间 / 供应商","请求 / 响应 / 计价模型","Token 输入 / 输出 / 缓存","估算费用","状态","耗时 / 首 Token / 速度"].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{logs?.records.map(r=><tr key={r.id} onClick={()=>{void command<UsageRecord>("get_usage_detail",{id:r.id}).then(setDetail).catch(e=>setError(errorOf(e).message));}}><td><button className="log-open" aria-label={`请求详情 ${r.id}`}>{date(r.createdAt)}</button><span>{r.providerName}</span></td><td>{r.requestModel??"未提供"}<span>{r.responseModel??"未提供"}</span><span>{r.billingModel??"未提供"}</span></td><td>{number(r.tokens.input)} / {number(r.tokens.output)}<span>{number(r.tokens.cacheRead)} / {number(r.tokens.cacheWrite)}</span></td><td>{money(r.cost.total)}<span>{r.cost.status==="partial"?"部分计价":""}</span></td><td><span className={r.outcome==="OK"?"usage-ok":"usage-failure"}>{r.status??"—"} {r.outcome}</span>{r.streaming&&<span>SSE / WS</span>}</td><td>{r.latencyMs} ms<span>{r.firstTokenMs==null?"未提供":`${r.firstTokenMs} ms`}</span><span>{speed(r)}</span></td></tr>)}</tbody></table>{!logs?.records.length&&<div className="usage-empty">当前范围没有明细</div>}</div><div className="usage-pagination"><span>{number(logs?.total??0)} 条 · 每页 20 条</span><button disabled={!page||busy} onClick={()=>setPage(p=>p-1)}>上一页</button><label>第 <input aria-label="日志页码" type="number" min="1" max={Math.max(1,Math.ceil((logs?.total??0)/20))} value={page+1} onChange={e=>{const n=Number(e.target.value);if(n>=1&&n<=Math.max(1,Math.ceil((logs?.total??0)/20)))setPage(n-1);}}/> / {Math.max(1,Math.ceil((logs?.total??0)/20))} 页</label><button disabled={busy||(page+1)*20>=(logs?.total??0)} onClick={()=>setPage(p=>p+1)}>下一页</button></div></section>}
 <div className="usage-status">更新于 {updated?new Date(updated).toLocaleTimeString():"—"}{settings&&!settings.settings.enabled?" · 已暂停记录":""}</div>
 </>}
 {detail&&<UsageDialog wide title="请求详情" close={()=>setDetail(null)}><Detail record={detail}/></UsageDialog>}
 {edit&&<UsageDialog title="记录设置" close={()=>setEdit(null)}><form className="usage-form" onSubmit={e=>{e.preventDefault();void changeSettings(edit);}}><label className="check-label"><input type="checkbox" checked={edit.enabled} onChange={e=>setEdit({...edit,enabled:e.target.checked})}/>记录网关用量</label><label>计价模型<select value={edit.modelSource} onChange={e=>setEdit({...edit,modelSource:e.target.value as "request"|"response"})}><option value="response">响应模型优先</option><option value="request">请求模型优先</option></select></label><label>成本倍率<input type="number" min="0" step="any" required value={edit.costMultiplier} onChange={e=>setEdit({...edit,costMultiplier:e.target.value})}/></label><label>明细保留天数<input type="number" min="1" max="3650" required value={edit.retentionDays} onChange={e=>setEdit({...edit,retentionDays:Number(e.target.value)})}/></label><details><summary>供应商成本倍率</summary>{data?.availableProviders.map(([id,name])=><label key={id}>{name}<input type="number" min="0" step="any" placeholder="继承全局" value={edit.providerMultipliers[id]??""} onChange={e=>{const m={...edit.providerMultipliers};if(e.target.value)m[id]=e.target.value;else delete m[id];setEdit({...edit,providerMultipliers:m});}}/></label>)}</details>{error&&<div className="form-error" role="alert">{error}</div>}<button className="primary" disabled={busy}>保存</button></form></UsageDialog>}
 </section>;
}
function GroupTable({rows,kind}:{rows:Group[];kind:string}) {return <section className="usage-card"><h2>{kind==="providers"?"供应商统计":"模型统计"}</h2><div className="usage-table-scroll"><table className="usage-table"><thead><tr><th>{kind==="providers"?"供应商":"计价模型"}</th><th>请求</th>{kind==="providers"&&<><th>成功 / 失败</th><th>成功率</th></>}<th>Token</th><th>估算费用</th><th>{kind==="providers"?"平均耗时":"平均费用"}</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td title={r.name}>{r.name}</td><td>{number(r.requests)}</td>{kind==="providers"&&<><td>{r.successes} / {r.requests-r.successes}</td><td>{r.requests?(r.successes/r.requests*100).toFixed(1):0}%</td></>}<td>{number(totalTokens(r.tokens))}</td><td>{money(r.cost)}</td><td>{kind==="providers"?`${Math.round(r.latencyMs/Math.max(1,r.requests))} ms`:r.cost===null?"未定价":money(String(Number(r.cost)/Math.max(1,r.requests)))}</td></tr>)}</tbody></table>{!rows.length&&<div className="usage-empty">暂无数据</div>}</div></section>;}
function Detail({record:r}:{record:UsageRecord}) {
 const entries: [string,unknown][]=[["请求 ID",r.id],["逻辑请求 ID",r.logicalId],["上游尝试",r.attempt+1],["供应商",r.providerName],["时间",date(r.createdAt)],["状态",`${r.status??"—"} ${r.outcome}`],["流式",r.streaming?"是":"否"],["请求模型",r.requestModel??"未提供"],["响应模型",r.responseModel??"未提供"],["计价模型",r.cost.pricingModel??r.billingModel??"未定价"],["服务等级",r.serviceTier??"未提供"],["倍率",r.multiplier],["总耗时",`${r.latencyMs} ms`],["首 Token",r.firstTokenMs===null?"未提供":`${r.firstTokenMs} ms`],["输出速度",speed(r)],["完整性",r.incomplete?"不完整":"完整"],["估算总费用",money(r.cost.total)],["价格版本",r.cost.version]];
 return <><dl className="usage-detail">{entries.map(([name,value])=><div key={name}><dt>{name}</dt><dd>{String(value)}</dd></div>)}</dl><table className="usage-table"><thead><tr><th>用量</th><th>Token</th><th>USD / 百万 Token</th><th>估算费用</th></tr></thead><tbody>{([['input','输入'],['output','输出'],['cacheRead','缓存读取'],['cacheWrite','缓存写入']] as const).map(([k,n])=><tr key={k}><td>{n}</td><td>{number(r.tokens[k])}</td><td>{r.cost.price?.rates[k]??"未定价"}</td><td>{money(r.cost[k])}</td></tr>)}</tbody></table>{r.cost.price&&<details><summary>价格快照 · {r.cost.price.source}</summary><PriceSnapshot price={r.cost.price}/></details>}</>;
}
function PriceSnapshot({price}:{price:Price}) {return <pre className="price-snapshot">{JSON.stringify({rates:price.rates,variants:price.variants},null,2)}</pre>;}
